# Article-Service Dockerfile
FROM openjdk:17-jdk-slim

WORKDIR /app

# Passe den JAR-Namen an
COPY target/article-service-0.0.1-SNAPSHOT.jar app.jar

# Exponierter Port (z.B. 8081)
EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
